### ISSUE TITLE
Some questions about downsampling of point clouds

### ISSUE THREAD

**Issue by jinhong-ni** [qinzheng93/GeoTransformer#31]
Hi there,

Really appreciate releasing your amazing work! I'm quite new to point clouds and I have some questions regarding downsampling of the point clouds.

Take 3DMatch as an example. The original raw dataset downloaded from PREDATOR is quite dense, and is preprocessed so that each grid size is 2.5cm. In your work, you further subsample the point clouds using KPConv (the first level downsampled points). My first question is what's the purpose of subsampling? Would a denser point cloud be more informative for registration?

Also, is there a specific reason you downsample the points further for dense point correspondences as I believe the preprocessed input data is already of density 2.5cm?

Last, is there a quick way to visualize the registration result for the 3DMatch benchmark? By running eval.py and test.py it seems to only produce the quantitative metrics.

Thanks for your patience and reply in advance!

**Comment by qinzheng93** [comment]
In 3DMatch, the original raw point clouds are fused from 50 consecutive RGB-D frames, and usually have more than 100k points. One one hand, they cannot be processed directly because they are too large. On the other hand, we actually do not need such dense point clouds to effectively understand the scene. So that's why PREDATOR and other methods preprocessed the point clouds with a voxel size of 2.5cm.

The insight of the following grid subsampling in the KPConv-based backbone is similar with that of FPN in image recognition tasks. KPConv has a limited receptive field, but we all know that the context in a larger scope help. So that's why we further downsample the point clouds into multiple resolution levels. One of the advantages of grid subsampling is the near-uniform sampling density. This is rather important for our geometric structure embedding as we leverage the spatial consistency between two sets of superpoints.

For dense point correspondences, we choose the points on the second level for two reasons. First, the points voxelized by 2.5cm are still too dense and too difficult to distinguish. Consider two points which are 2.5cm apart on a chair. I don't think they have much differences in structure. Second, matching on the second level is more computationally-efficient.

For visualization, you can refer to #28 .

**Comment by jinhong-ni** [comment]
Thanks for your detailed answer! That clarifies everything.

**Comment by jinhong-ni** [comment]
Hi Qin,

Thanks again for your great answer previously. I have one further question regarding the subsampling list that wish you could please clarify a bit.

In the case of 3DMatch, I notice for each point cloud there are 3 subsamplings, of shape (10110, 38), (2850, 36), and (790, 36) respectively. I assume the first dimension corresponds to the number of downsampled points in each strided KPConv. Originally, there are 38059 points in the cloud. 

My questions are how the numbers of downsampled points are determined, and what the second dimension of these subsamplings indicates. Sorry for any potential dumb questions, but really struggling to understand these.

Much appreciated for your patience and reply!

**Comment by qinzheng93** [comment]
1. The number of downsampled points is adaptively determined by grid subsampling. It is not fixed for all point clouds. For example, the input point cloud is voxelized by 2.5cm, the point cloud at the second level is voxelized by 5cm, and the point cloud at the third level is voxelized by 10cm, etc.
2. The second number is the number of neighbors for each point. It is determined by two steps: first, compute the numbers of neighbors within a radius for all points; second, choose the number of neighbors that covers 80% of the points.

**Comment by jinhong-ni** [comment]
Many thanks!
